### ISSUE TITLE
58067 - Gramophone Creek

### ISSUE THREAD

**Issue by lucy-schick** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#37]
- [x] photos show one of the culverts has a significant outlet drop but not mentioned in comments, so added note to comments.
- [x] Overall comments are very sparse, added mention of ST and RB FISS sites upstream.
- [x] Ef site with fish caught but `fish_observed_yes_no` was set to `no`, changed to `yes`
- [x] 2 culverts but only one id, added second `chris_culvert_id`
- [ ] Can see 2023 ef downstream point but not upstream point
- [ ] previous PSCIS assessment from 2012 marked as a barrier.

**Comment by NewGraphEnvironment** [comment]
closing in favour of https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/issues/145

**Comment by NewGraphEnvironment** [comment]
Fish point location is very important here as it is an indication of distribution limit at time of survey. At time of issue repoening the captured fish are reported within `58067_ds` but that site began at Wiggs Creek (1.1km upstream of the canyon/chute).  the fish were captured within `58067_ds2`.

This needs to be changed in `data/habitat_confirmations.xls` (aka. fish data submission ) so that coho don't show up as captured waaaay upstream in FISS.  

Unfortunately, there is no mechanism for accurately goereferenceing fish in the fish data submission form (just the site UTM) so having the `CO` show up near the Bulkley River will need to do. However, for our internal mapping purposes and data presentation on github we will custom input the UTM into `scripts/tables.R` (within the `hab_loc2` object) so that we get our fish point falling at the right spot.

Will do the custom UTM bomb in `tables.R` but I think it will need to be redone when it is fixed in the fish data submission excel file (ie. habitat_confirmations.xls). Will reference this issue to try to make it easier to untangle afterwards.

**Comment by NewGraphEnvironment** [comment]
going to fix this in `main` branch version of `habitat_confirmations.xls` so `tables.R` can persist when the change is made in the other branch dealing with  `habitat_confirmations.xls`.  Will ignore `data/backup` csvs for now to try to avoid merge conflicts. `git` can't see the actual `habitat_confirmations.xls` so that shouldn't matter.

**Comment by lucy-schick** [comment]
confirming that fish capture location is` 58067_ds2` in `habitat_confirmations.xls`. will close

![Screen Shot 2024-06-11 at 11 33 29 AM](https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/assets/151881303/77ca2fdf-7a68-4a1a-aff9-12582456f913)
